stages:
  - build
  - test
  - deploy

variables:
  DOCKER_IMAGE: ${CI_REGISTRY_IMAGE}:${CI_COMMIT_REF_SLUG}

build:
  stage: build
  image: golang:1.21
  script:
    - go mod download
    - go build -o app ./cmd/cli
  artifacts:
    paths:
      - app

test:
  stage: test
  image: golang:1.21
  script:
    - go test ./...

deploy:
  stage: deploy
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker build -t $DOCKER_IMAGE .
    - docker push $DOCKER_IMAGE
  only:
    - main
